"""16.08.2023-12:50:48

Revision ID: 2a5d261a51f5
Revises: c770429165fa
Create Date: 2023-08-16 12:50:49.076034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5d261a51f5'
down_revision = 'c770429165fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
