"""16.08.2023-13:05:54

Revision ID: 2fcb4768247e
Revises: cf06f282c5ab
Create Date: 2023-08-16 13:05:55.181904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fcb4768247e'
down_revision = 'cf06f282c5ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
