"""16.08.2023-12:58:07

Revision ID: 872232f17595
Revises: e601bc58761f
Create Date: 2023-08-16 12:58:08.421057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872232f17595'
down_revision = 'e601bc58761f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
