"""15.08.2023-17:15:40

Revision ID: ceac358cab0a
Revises: 82a7b0eace99
Create Date: 2023-08-15 17:15:40.955809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceac358cab0a'
down_revision = '82a7b0eace99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
