"""16.08.2023-13:04:55

Revision ID: cf06f282c5ab
Revises: 872232f17595
Create Date: 2023-08-16 13:04:55.975905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf06f282c5ab'
down_revision = '872232f17595'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
