"""16.08.2023-12:53:38

Revision ID: e601bc58761f
Revises: 2a5d261a51f5
Create Date: 2023-08-16 12:53:38.734442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e601bc58761f'
down_revision = '2a5d261a51f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
